[libraries]
defaultlib.files = [
  'combi.vhd',
  'etages.vhd',
  'mem.vhd',
  'proc.vhd',
  'reg_bank.vhd',
  'aleas.vhd',
  'test_etage_fe.vhd',
  'test_etage_de.vhd',
  'test_etage_ex.vhd',
  'test_controle.vhd',
  'test_aleas.vhd'
]
